name: outlook
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  intl_utils: ^2.8.8
  flutter_intl: ^0.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/Icons/
    - assets/images/
    - assets/fonts/
    - lib/l10n/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-VariableFont_wght.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
          weight: 400

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n
